### ISSUE TITLE
Build FAIL on Windows 7 (VS2013)

### ISSUE THREAD

**Issue by PatSmuk** [zone117x/node-multi-hashing#2]
This modules fails to build for me. The log is here: http://paste2.org/NnYDEGDn

It seems that because keccak.c and skein.c exist in the root and sha3 dirs, the OBJs for them are overwriting each other, and then it fails to link.

**Comment by erm3nda** [comment]
I have problems too compiling that in Windows with Visual Studio. I've been able to compile from a Linux machine. Don't know if I can compile it from Linux to Windows... but i can't run many programs due to that dependancy.
