### ISSUE TITLE
Cryptonight variant for v7 seems incorrect

### ISSUE THREAD

**Issue by agpappas** [zone117x/node-multi-hashing#51]
I tried the master branch to hash the test sets found here
https://github.com/monero-project/monero/blob/master/tests/hash/tests-slow-1.txt

using variant 1 and the outputs for all tests are incorrect. Furthermore, the final changes in the official Monero project seem a bit different than the ones merged in this project.

Have you tested the relevant PR and found it to be correct?

**Comment by perl5577** [comment]
I confirm variant7 is not OK
EX:
"0707a4f8bdd50509e32c1357fad5eef02811c09e2331088699b356ca4bd9438c21884e13ba34b706000000a7c827fa9b9c3dec13e5e2feb9a6266c8f1c866209343720e3823edecf4e2cc001" 
Find:
4f ae 9a 92 29 6a cc fe 67 54 28 b5 1b f2 d7 aa 8f 6d 70 40 c8 28 52 c7 a1 91 fa 3c 7d 81 0c 82
Expect:
da 9b b5 11 3a de 4d f7 68 f8 a1 81 c4 f9 d0 e3 45 71 48 0c 7f 03 3c 10 bc b7 2b b6 f4 26 5f 02

**Comment by grunjol** [comment]
I just hashed `0707a4f8bdd50509e32c1357fad5eef02811c09e2331088699b356ca4bd9438c21884e13ba34b706000000a7c827fa9b9c3dec13e5e2feb9a6266c8f1c866209343720e3823edecf4e2cc001`
with the code from master and its returning 
`da 9b b5 11 3a de 4d f7 68 f8 a1 81 c4 f9 d0 e3 45 71 48 0c 7f 03 3c 10 bc b7 2b b6 f4 26 5f 02`

**Comment by agpappas** [comment]
The issue was opened before #53 
I suppose now this issue should be closed.
